import { Code2, Layout, Database, Cloud } from 'lucide-react';

export const skills = [
    {
        id: 'backend',
        name: 'Backend Development',
        icon: Database,
        description: 'Creating robust and scalable server-side applications.',
        proficiency: 85,
        tools: [
            'Node.js',
            'Express',
            'NestJS',
            'PHP',
            'LARAVEL',
            'MySQL',
            'PostgreSQL',
            'MSSQL',
            'MongoDB',
            'Microservices',
        ],
        accentColor: '#000',
        size: 'default',
    },
    {
        id: 'frontend',
        name: 'Frontend Development',
        icon: Layout,
        description: 'Building responsive and interactive user interfaces.',
        proficiency: 70,
        tools: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Bootstrap', 'Framer Motion'],
        accentColor: '#000',
        size: 'default',
    },
    {
        id: 'devops',
        name: 'DevOps',
        icon: Cloud,
        description: 'Managing deployment and infrastructure automation.',
        proficiency: 70,
        tools: ['Docker', 'AWS', 'Azure', 'CI/CD'],
        accentColor: '#000',
        size: 'default',
    },
    {
        id: 'programming',
        name: 'Programming',
        icon: Code2,
        description: 'Core programming languages and software development.',
        proficiency: 80,
        tools: ['JavaScript', 'TypeScript', 'PHP', 'Rust', 'Java', 'Python'],
        accentColor: '#000',
        size: 'default',
    },
];
